server:
  port: 8888
spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: keynote-service
              uri: lb://Keynote-service
              #            uri: http://localhost:8080
              predicates:
                - Path=/api/keynotes/**
            - id: conference-service
              uri: lb://Conference-service
              #            uri: http://localhost:8081
              predicates:
                - Path=/api/conferences/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true